---
- hosts: all

  tasks:
  
    - name: Repo epel-release
      yum:
        name: epel-release
        state: latest

    - name: update cache
      yum:
        update_cache: yes

    - name: Install software
      # bash-completion --- bash 补全
      # htop            --- top 改进版
      yum:
        name:
          - bash-completion
          - htop
          - net-tools
          - tar
          - vim
          - wget
          - bash-completion
        state: latest

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Stop service Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled