---
- hosts: all

  tasks:
  - name: prevent brute force -- system-auth -- CentOS 7
    lineinfile:
      path: /etc/pam.d/system-auth-ac
      insertbefore: "auth        required      pam_env.so"
      line: "auth        required      pam_tally2.so deny=3 unlock_time=300 even_deny_root root_unlock_time=300"
    when: ansible_distribution_major_version == "7"

  - name: prevent brute force -- sshd -- CentOS 7
    lineinfile:
      path: /etc/pam.d/sshd
      insertafter: "#%PAM-1.0"
      line: "auth       required     pam_tally2.so deny=3 unlock_time=300 even_deny_root root_unlock_time=300"
    when: ansible_distribution_major_version == "7"
