---
- hosts: all

  tasks:
  
    - name: Repo epel-release
      ansible.builtin.yum:
        name: epel-release
        state: latest

    - name: update cache
      ansible.builtin.yum:
        update_cache: yes

    - name: Install software
      # bash-completion --- bash 补全
      # htop            --- top 改进版
      ansible.builtin.yum:
        name:
          - bash-completion
          - htop
          - net-tools
          - tar
          - vim
          - wget
          - bash-completion
        state: latest

    - name: upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Stop service Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Copy banner file for sshd
      ansible.builtin.copy:
        src: files/ssh/sshd_banner
        dest: /etc/ssh/
        owner: root
        group: root
        mode: '0644'

    - name: Copy profile file for motd
      ansible.builtin.copy:
        src: files/dymotd.sh
        dest: /etc/profile.d/
        owner: root
        group: root
        mode: '0644'