---
- hosts: all

  tasks:
  - name: set password expire
    lineinfile:
      path: /etc/login.defs
      regexp: "{{ item.regexp_string }}"
      line: "{{ item.rule }}"
    with_items:
      - { regexp_string: "^PASS_MAX_DAYS", rule: "PASS_MAX_DAYS   90"}
    when: ansible_distribution_major_version == "7"

  - name: 1.Centos7 set password quality
    lineinfile:
      path: /etc/security/pwquality.conf
      regexp: "{{ item.regexp_string }}"
      line: "{{ item.rule }}"
    with_items:
      - { regexp_string: "minlen", rule: "minlen = 8"}
      - { regexp_string: "dcredit", rule: "dcredit = -1"}
      - { regexp_string: "lcredit", rule: "lcredit = -1"}
      - { regexp_string: "ocredit", rule: "ocredit = -1"}
      - { regexp_string: "ucredit", rule: "ucredit = -1"}
    when: ansible_distribution_major_version == "7"
