---
- name: Public key is deployed to managed hosts for Ansible.
  hosts: all

  # 使用时，应增加 --ask-pass 参数。

  tasks:
  - name: Ensure key is in root's ~/.ssh/authorized_hosts 
    authorized_key:
       user: root
       state: present
       key: '{{ item }}'
    with_file:
       - ~/.ssh/id_rsa.pub
